# Generated by Django 5.1.2 on 2024-10-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('reliability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RssData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
